version: '3'

services:
  redis:
    image: redis:7.0.5
    container_name: my-redis-container
    ports:
      - 6379:6379
    networks:
      - crawler
  mysql:
    image: mysql:5.7
    container_name: my-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - crawler

networks:
  crawler: